HTML事前課題 HTMLコーディング
kakudaisuke/quelcode-html pull request #1
Opened 2020-07-28 07:25 UTC by kakudaisuke

よろしくお願いします。

2020-07-29 03:21 UTC, yusaku-inamura requested changes
確認しました。
全体を通しての印象としては、初心者とは思えないほどいい感じにマークアップできていると思います。
各要素やブロックの意味を考えたり、cssを記述する際のことを考えてブロック分けできたりするとよりぐっどですね👍

まずは指摘事項の確認お願いします。

2020-07-29 03:21 UTC, yusaku-inamura commented on nri/index.html
> +      <li><a href="#"><h2>NRI JOURNAL</h2></a></li>
ここら辺の文言ちょっとおかしいですね。
元のnriのページとよく見比べてみましょう。

2020-07-29 03:21 UTC, yusaku-inamura commented on nri/index.html
> +      <li><a href="#"><h2>NRI JOURNAL</h2></a></li>
こちらも項目名がお手本とあっていない気が。

2020-07-29 03:21 UTC, yusaku-inamura commented on nri/index.html
> +  </div><!-- .share -->
ここらへんインデントがひとつ足りないですね。
表示には関係ないですが、読みやすさは保守性に繋がるため運用していく上で非常に重要な要素です。
極力気にしていけるようにしましょう。
エディタのプラグインなどで自動でコードを整形してくれるように設定するのが手軽さでも確実性でも一番ですね。

2020-07-29 03:21 UTC, yusaku-inamura commented on nri/index.html
> +  <div class="follow-us">
お手本のnriの他のページを見るとわかるのですが、この要素から下は共通のフッター として使用されているように見受けられます。
そのため、footerタグの中に入れてしまっても良い気がしますね。

2020-07-29 03:21 UTC, yusaku-inamura commented on nri/index.html
> +</html>
ファイルの末尾には必ず改行をつけましょう。(htmlだけではなく他のファイルも全て)
ざっくり理由を言うと、posixという各種OSにおけるアプリケーションインターフェース実装の共通規格にて、 `行は改行にて終わり、ファイルは行の集合からなる` と定義されているからです。
・・・とは言ったものの、細かい理由は今は無視して必ず末尾に改行を一行入れるんだなと覚えてもらえればそれで十分です。

2020-07-29 03:21 UTC, yusaku-inamura commented on nri/index.html
> +
不要な改行は削除しましょう。

2020-07-29 03:21 UTC, yusaku-inamura commented on nri/index.html
> +  <div class="page-navigation">
この要素は `NRIのデジタルビジネス戦略` の文脈に対する補足情報なので、articleの中に入ってしまってもいいような気がしますね 🤔

2020-07-29 04:01 UTC, kakudaisuke commented on nri/index.html
> +  </div><!-- .share -->
インデント気をつけていきます！

2020-07-29 04:03 UTC, kakudaisuke commented on nri/index.html
> +  <div class="follow-us">
なるほど。他のページとの兼ね合いも今後気をつけます！

2020-07-29 04:51 UTC, kakudaisuke commented on nri/index.html
> +</html>
posixというものを初めて知りました。末尾に改行を入れることを覚えておきます。

2020-07-29 04:55 UTC, kakudaisuke commented on nri/index.html
> +
わかりました。

2020-07-29 05:00 UTC, kakudaisuke commented on nri/index.html
> +  <div class="page-navigation">
この`<div class="page-navigation">`をarticleの中に入れてしまうということですね？なるほど。本文ではないかなと思って入れなかったのですが、入れて修正します！

2020-07-29 05:00 UTC, kakudaisuke commented on nri/index.html
> +      <li><a href="#"><h2>NRI JOURNAL</h2></a></li>
失礼しました！

2020-07-29 05:00 UTC, kakudaisuke commented on nri/index.html
> +      <li><a href="#"><h2>NRI JOURNAL</h2></a></li>
こちらも失礼しました！

2020-07-30 05:12 UTC, Yuzunoha approved these changes
OKだと思います！！CSSに進みましょうっ

2020-07-31 02:05 UTC, piasoratech requested changes
画像ファイルがプッシュされていないようですので、使用している画像などが表示される状態にして再提出をお願いします。

2020-07-31 02:34 UTC, piasoratech requested changes
以下特に気になった部分です。他にも細かい部分で本家のサイトと見た目が違う部分があるので、よく確認をして修正をお願いします。
- こちらの部分の上段の大きさが本家サイトと異なるのと、ホバー時の挙動が実装されていないので確認と修正をお願いします。
![image](https://user-images.githubusercontent.com/57445698/88993596-5ca63780-d321-11ea-926a-d7b6a09fb91e.png)
- フッターとの区切り線が本家サイトでは端まであるので、確認と修正をお願いします。
![image](https://user-images.githubusercontent.com/57445698/88993674-8d866c80-d321-11ea-973c-4ade37de0269.png)
- 別途指摘事項をコード内でも行っているので、全体を確認して修正をお願いします。

2020-07-31 02:34 UTC, piasoratech commented on nri/css/style.css
> +  /* 全部効かない... */
不要な部分はコメントとして残さずに消しましょう

2020-07-31 07:00 UTC, kakudaisuke commented on nri/css/style.css
> +  /* 全部効かない... */
わかりました。ありがとうございます。

2020-07-31 07:39 UTC, piasoratech approved these changes
OKです！！

2020-07-31 08:18 UTC, kakudaisuke commented
> OKです！！

ありがとうございます！！

2020-08-14 05:54 UTC, merged